# -*- coding: utf-8 -*-
"""Tugas1MechineLearning_Dela Puspita Helmi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PESIp3BsJQpKK4ZoUZcqj8E_Z571HL4e
"""

import pandas as pd
knn = pd.read_csv('/content/KNNAlgorithmDataset.csv')

knn.info()

knn.head()

#memisakhan atribut dengan label dimana x itu atribut dan y itu label
X = knn [['radius_mean','radius_se','radius_worst']]
y = knn ['diagnosis']


#membagi dataset menjadi data latih dan data uji
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.1, random_state=123)

from sklearn.tree import DecisionTreeClassifier

#membuat model decision tree
tree_model= DecisionTreeClassifier()

#melatih model menggunakan data latih dengan fungsi fit
tree_model= tree_model.fit(X_train,y_train)

#evaluasi model untuk meguji seberapa baik model yang digunakan dan akurasi

from sklearn.metrics import accuracy_score

y_pred =  tree_model.predict(X_test)

accuracy_score =round(accuracy_score(y_pred, y_test), 3)

print('Accuracy: ',accuracy_score)